apiVersion: v1 
kind: Pod 
metadata: 
  name: secret-bootcamp
spec: 
  volumes:
    - name: secret-volume
      secret:
        secretName: simple-secret
  containers: 
  - name: secret-bootcamp
    image: alpine:latest 
    command: ["sleep", "9999"]
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
    env: 
      - name: SECRET_USERNAME 
        valueFrom: 
          secretKeyRef: 
            name: simple-secret 
            key: username 
      - name: SECRET_PASSWORD 
        valueFrom: 
          secretKeyRef: 
            name: simple-secret 
            key: password 
  restartPolicy: Never